"""Browser checks against the shipped HTML/CSS/JS. See README for the in-memory harness."""
from pathlib import Path
import sys,json,re,time,os,subprocess,urllib.request,urllib.error,hashlib
from playwright.sync_api import sync_playwright
from browser_helper import load,launch
R=Path(__file__).resolve().parents[2]
O=R/'test-output';O.mkdir(exist_ok=True)
results=[]
def check(name,ok,detail=None):
    results.append({'test':name,'pass':bool(ok),'detail':detail})
    if not ok:
        (O/'browser-results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2))
        raise AssertionError((name,detail))
    print('PASS',name,flush=True)
removed={'hefesto-distribuicao','resultados-copa-energia','resultados-boticario','painel-gerencial-santander','painel-operacional-santander','painel-gerencial-zurich','painel-individual-zurich'}
projects=json.loads((R/'data/projects.json').read_text())
with sync_playwright() as p:
    b=launch(p)
    page=b.new_page(viewport={'width':1600,'height':1000},reduced_motion='reduce')
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('console',lambda m:errors.append(m.text) if m.type in ['warning','error'] else None)
    load(page,R);page.wait_for_timeout(1400)
    check('catalogue has 14 pre-rendered cards',page.locator('.catalog-card').count()==14)
    check('no removed IDs in runtime catalogue', not removed.intersection(page.evaluate('JSON.parse(document.querySelector("#projectData").textContent).map(p=>p.id)')))
    check('continuous motion remains enabled',page.evaluate('document.documentElement.dataset.motionState')=='on')
    check('no global or carousel pause controls',page.locator('#motionQuick,#motionToggle,#slidePause').count()==0)
    check('tilted hero restored',page.locator('#showcaseSheet').evaluate('el=>Math.abs(new DOMMatrix(getComputedStyle(el).transform).b)>.01'))
    check('floating labels restored',page.locator('.data-label').is_visible() and page.locator('.insight-sticker').is_visible())
    for i in range(5):
        page.wait_for_function('document.querySelector("#showcaseImage").complete && document.querySelector("#showcaseImage").naturalWidth>0')
        ident=page.locator('#showcaseLink').get_attribute('data-open-project')
        check(f'hero image {i+1} renders a retained project',ident not in removed,ident)
        page.locator('#slideNext').click();page.wait_for_timeout(240)
    before=page.locator('#showcaseLink').get_attribute('data-open-project')
    page.locator('#slideNext').focus()
    rect=page.locator('#showcaseLink').bounding_box();page.mouse.move(rect['x']+100,rect['y']+100)
    page.wait_for_timeout(6800)
    check('carousel advances while hovered and keyboard-focused',page.locator('#showcaseLink').get_attribute('data-open-project')!=before)
    c1=page.locator('#ambientCanvas').evaluate('el=>el.toDataURL()');page.wait_for_timeout(250)
    check('animated background changes frames',c1!=page.locator('#ambientCanvas').evaluate('el=>el.toDataURL()'))
    page.locator('#slidePrev').click();page.wait_for_timeout(300)
    page.mouse.move(1,1);page.wait_for_timeout(400)
    page.screenshot(path=str(O/'abertura.png'))
    # All icon slots exchange in-place and retain a single SVG child.
    for sel in ['.brand','.hero-signature','.manifesto-bottom','.portrait-topline','.contact-spark']:
        slot=page.locator(sel+' [data-tool-rotator]')
        slot.scroll_into_view_if_needed();page.wait_for_timeout(450)
        first=slot.get_attribute('data-tool-rotator');box=slot.bounding_box()
        page.wait_for_timeout(2950)
        check(f'{sel}: icon switches',first!=slot.get_attribute('data-tool-rotator'))
        check(f'{sel}: only one icon at a time',slot.locator('svg').count()==1)
        after=slot.bounding_box()
        check(f'{sel}: fixed square slot',abs(box['width']-box['height'])<1 and abs(box['width']-after['width'])<1,box)
    slot=page.locator('.portrait-topline .tool-rotator')
    check('portrait icon keeps original 34px size',abs(slot.bounding_box()['width']-34)<1)
    page.locator('.tech-line').scroll_into_view_if_needed();page.wait_for_timeout(450)
    check('tools list has no interactive elements',page.locator('.tool-list button,.tool-list a,.tool-list [tabindex],.tool-list [role="button"]').count()==0)
    for li in page.locator('.tool-list li').all():
        m=li.evaluate('el=>{const s=getComputedStyle(el);return {text:el.textContent,bg:s.backgroundColor,border:s.borderTopWidth,shadow:s.boxShadow,radius:s.borderRadius,cursor:s.cursor,fill:getComputedStyle(el.querySelector("svg path")).fill}}')
        check('plain monochrome tool '+m['text'],m['bg']=='rgba(0, 0, 0, 0)' and m['border']=='0px' and m['shadow']=='none' and m['radius']=='0px' and m['cursor']=='default' and m['fill']=='rgb(255, 255, 255)',m)
    page.locator('.tech-line').screenshot(path=str(O/'ferramentas-sem-bordas.png'))
    check('technology marquee has real SVGs, no spark symbols',page.locator('.marquee-track svg').count()==12 and '✳' not in page.locator('.tech-marquee').inner_text())
    page.locator('.system-card').scroll_into_view_if_needed();page.wait_for_timeout(400)
    for key,word in [('python','Python'),('looker','Looker Studio'),('javascript','JavaScript'),('sql','SQL')]:
        node=page.locator(f'[data-skill="{key}"]');node.click();page.wait_for_timeout(160)
        check('map commentary '+key,word in page.locator('#systemTooltipTitle').inner_text() and node.get_attribute('aria-pressed')=='true')
    page.locator('[data-skill="python"]').focus();page.keyboard.press('Enter')
    check('map works with keyboard',page.locator('[data-skill="python"]').get_attribute('aria-pressed')=='true')
    page.locator('.system-card').screenshot(path=str(O/'mapa-interativo.png'))
    # Search and navigation use the same cleaned source as the static page.
    page.locator('#projectSearch').fill('Copa')
    check('Copa search returns only COPA - Tempos','1 de 1' in page.locator('#catalogCount').inner_text() and page.locator('.catalog-card:visible h3').inner_text()=='COPA - Tempos')
    page.locator('#projectSearch').fill('Boticário')
    check('Boticário search returns only Carteirização Boticário','1 de 1' in page.locator('#catalogCount').inner_text() and 'Carteirização' in page.locator('.catalog-card:visible h3').inner_text())
    page.locator('#projectSearch').fill('zz_not_a_project')
    check('empty search has an actionable empty state',page.locator('#emptyState').is_visible())
    page.locator('#emptyReset').click()
    page.locator('[data-filter="aplicacao"]').click()
    check('applications filter shows four remaining apps','4 de 4' in page.locator('#catalogCount').inner_text())
    page.locator('[data-filter="todos"]').click()
    check('empty automation category removed',page.locator('[data-filter="automacao"]').count()==0)
    while page.locator('#loadMore').is_visible():page.locator('#loadMore').click();page.wait_for_timeout(500)
    check('load more reveals all 14 projects',page.locator('.catalog-card:visible').count()==14)
    for project in projects:
        page.locator(f'#caso-{project["id"]} h3 a').click();page.wait_for_timeout(140)
        img=page.locator('#caseMedia img');page.wait_for_function('document.querySelector("#caseMedia img").complete && document.querySelector("#caseMedia img").naturalWidth > 0')
        check('project dialog opens '+project['id'],page.locator('#caseTitle').inner_text()==project['title'])
        m=img.evaluate('el=>({height:el.getBoundingClientRect().height,width:el.getBoundingClientRect().width,natural:el.naturalWidth,fit:getComputedStyle(el).objectFit})')
        check('compact original screenshot '+project['id'],m['height']<=361 and m['width']<=m['natural']+1 and m['fit']=='contain',m)
        if project['id']=='copa-tempos':
            page.screenshot(path=str(O/'projeto-copa-tempos.png'))
            page.locator('#caseMedia button').click();page.wait_for_timeout(120)
            check('separate image enlargement opens',page.locator('#imageDialog').evaluate('el=>el.open'))
            page.keyboard.press('Escape')
        check('no project video '+project['id'],page.locator('video').count()==0)
        page.locator('#closeCase').click()
    page.locator('.portrait-composition').scroll_into_view_if_needed();page.wait_for_timeout(500)
    image=page.locator('.portrait-photo img');image.hover();page.wait_for_timeout(300)
    check('portrait has no mouse filter or transform',image.evaluate('el=>getComputedStyle(el).filter==="none"&&getComputedStyle(el).transform==="none"'))
    page.locator('.portrait-composition').screenshot(path=str(O/'foto-sem-efeito.png'))
    page.locator('.copy-email').scroll_into_view_if_needed();page.wait_for_timeout(500)
    centers=page.locator('.copy-email').evaluate('el=>{const a=el.getBoundingClientRect(),b=el.querySelector("svg").getBoundingClientRect();return {dx:Math.abs(a.x+a.width/2-b.x-b.width/2),dy:Math.abs(a.y+a.height/2-b.y-b.height/2)}}')
    check('copy icon is centered',centers['dx']<1 and centers['dy']<1,centers)
    page.locator('.copy-email').click();page.wait_for_timeout(150)
    check('copy-email action gives feedback',page.locator('#toast').evaluate('el=>el.classList.contains("is-visible")'))
    for cls,url in [('social-linkedin','https://www.linkedin.com/in/lestarangelo/'),('social-github','https://github.com/lestardeangelo')]:
        link=page.locator('.'+cls)
        check('social link preserved '+cls,link.get_attribute('href')==url and link.locator('svg.tool-icon').count()==1)
        check('social link has no badge '+cls,link.evaluate('el=>getComputedStyle(el).borderTopWidth==="0px"&&getComputedStyle(el).backgroundColor==="rgba(0, 0, 0, 0)"'))
    page.locator('.site-footer').screenshot(path=str(O/'redes-sociais.png'))
    for width,height in [(320,800),(390,844),(600,900),(768,1024),(960,900),(1100,900),(1366,768),(1600,1000),(1920,1080),(2560,1440)]:
        page.set_viewport_size({'width':width,'height':height});page.evaluate('scrollTo({top:0,behavior:"instant"})');page.wait_for_timeout(350)
        check(f'no horizontal overflow {width}px',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
        header=page.locator('.header-inner').evaluate('el=>[...el.children].filter(x=>getComputedStyle(x).display!=="none").map(x=>({left:x.getBoundingClientRect().left,right:x.getBoundingClientRect().right}))')
        check(f'header elements do not overlap {width}px',all(header[i]['right']<=header[i+1]['left']+1 for i in range(len(header)-1)),header)
        page.locator('.tech-line').scroll_into_view_if_needed();page.wait_for_timeout(100)
        check(f'plain tools fit the viewport {width}px',page.locator('.tool-list').evaluate('el=>el.getBoundingClientRect().right<=innerWidth+1 && el.scrollWidth<=el.clientWidth+1'))
    page.set_viewport_size({'width':390,'height':844});page.evaluate('scrollTo({top:0,behavior:"instant"})');page.wait_for_timeout(600)
    page.locator('.menu-toggle').click();check('mobile menu opens',page.locator('#mobileNav').is_visible())
    page.keyboard.press('Escape');check('mobile menu closes',page.locator('#mobileNav').is_hidden())
    page.screenshot(path=str(O/'mobile-abertura.png'))
    page.locator('.tech-line').scroll_into_view_if_needed();page.wait_for_timeout(400);page.screenshot(path=str(O/'mobile-ferramentas.png'))
    page.locator('.site-footer').scroll_into_view_if_needed();page.wait_for_timeout(400);page.screenshot(path=str(O/'mobile-contato.png'))
    check('no JavaScript errors or warnings',not errors,errors)
    b.close()
(O/'browser-results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2))
print('TOTAL',len(results))
